export const useReport = defineStore("report", {
  state: () => ({
    sample: [],
    company_info_receipt: {
      address_th: "",
      address_en: "",
      name_th: "",
      name_en: "",
      tax_id: "",
      branch_no: "",
      sub_district: null,
    },
    other_address: {
      address_th: "",
      address_en: "",
      sub_district: null,
    },
    company_info_person: {
      first_name: "",
      last_name: "",
      position: "",
      email: "",
      line_id: "",
      telephone: "",
      mobile: "",
    },
    company_info_test_report: {
      address_th: "",
      address_en: "",
      name_th: "",
      name_en: "",
      tax_id: "",
      branch_no: "",
      sub_district: null,
    },
    is_general_info: false,
    is_research: false,
    is_domestic_consume: false,
    is_export_to_country: false,
    other_objective: "",
    delivery_means: null,
    other_delivery_means: "",
    is_email_noti: false,
    is_line_noti: false,
    by_post: null,
    remark: "",
    country: "",
  }),
  actions: {},
});
